model:
  target: Models.interpretable_diffusion.gaussian_diffusion.Diffusion_TS
  params:
    seq_length: 48
    feature_size: 1
    n_layer: 3
    d_model: 64  # 4 X 16
    timesteps: 100
    sampling_timesteps: 52
    loss_type: 'l1'
    beta_schedule: 'cosine'
    n_heads: 4
    mlp_ratio: 4
    attn_pdrop: 0       # 你想用多少就填多少，0就是不加
    resid_pdrop: 0
    kernel_size: 1
    padding_size: 0

solver:
  base_lr: 1.0e-4
  max_epochs: 14000
  results_folder: ./Checkpoints_traffic
  gradient_accumulate_every: 2
  save_cycle: 1400  # max_epochs // 10
  ema:
    decay: 0.999
    update_interval: 10

  scheduler:
    target: engine.lr_sch.ReduceLROnPlateauWithWarmup
    params:
      factor: 0.5
      patience: 1200
      min_lr: 1.0e-5
      threshold: 1.0e-1
      threshold_mode: rel
      warmup_lr: 1.0e-4
      warmup: 500
      verbose: False
  cfg_scale: 1.2

dataloader:
  train_dataset:
    target: Utils.Data_utils.real_datasets.CustomDataset
    params:
      name: traffic_48_SplitText
      feature_size: 1
      proportion: 0.7  # Set to rate < 1 if training conditional generation
      data_root: ./Data/datasets
      window: 48  # seq_length
      save2npy: True
      neg_one_to_one: True
      seed: 123
      period: train
      condition_dropout_prob: 0.3

  test_dataset:
    target: Utils.Data_utils.real_datasets.CustomDataset
    params:
      name: traffic_48_SplitText
      feature_size: 1
      proportion: 0.7 # rate
      data_root: ./Data/datasets
      window: 48  # seq_length
      save2npy: True
      neg_one_to_one: True
      seed: 123
      period: test
      style: separate
      distribution: geometric
      condition_dropout_prob: 0.3
    coefficient: 1.0e-2
    step_size: 5.0e-2
    sampling_steps: 250

  batch_size: 128
  sample_size: 256
  shuffle: True